name: test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Google Drive
        run: |
          mkdir GoogleDrive
          Invoke-WebRequest -Uri https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe -OutFile GoogleDrive/GoogleDriveSetup.exe
          ls GoogleDrive/
          
      - name: Download Win32 content prep tool
        run: |
          git clone https://github.com/Microsoft/Microsoft-Win32-Content-Prep-Tool Win32ContentPrepTool
          ls Win32ContentPrepTool/
          
      - name: Run tool
        run: |
          mkdir Output
          Win32ContentPrepTool/IntuneWinAppUtil.exe -c GoogleDrive -s GoogleDrive/GoogleDriveSetup.exe -o Output
          ls Output
          
      - name: Save as artifact
        uses: actions/upload-artifact@v3
        with:
          name: GoogleDriveSetup.intunewin
          path: Output/GoogleDriveSetup.intunewin
          
           
      
      

